#!/bin/sh

export PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin

# Redirect stderr to stdout for all services to ensure
# preserving the order between stdout and stderr.
exec runsvdir -P /etc/service 2>&1
